spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mariadb://192.168.1.3:3306/identity_service?createDatabaseIfNotExist=true
    driverClassName: "org.mariadb.jdbc.Driver"
    username: "root"
    password: "@Softz#vn#9999"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
  servlet:
    context-path: /identity

jwt:
  issuer: softz.com
  key: 6jalc3yn5pndwmvhwjzwkp81iq05w7u39ue0yyemxnsuw155if74ufd6qo5bd7e8
  ttl: 3360
